import 'package:hive/hive.dart';

part 'news_source.g.dart';

@HiveType(typeId: 1)
class NewsSource extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String name;
  
  @HiveField(2)
  final String rssUrl;
  
  @HiveField(3)
  final String? logoUrl;
  
  @HiveField(4)
  final String categoryId;

  NewsSource({
    required this.id,
    required this.name,
    required this.rssUrl,
    required this.categoryId,
    this.logoUrl,
  });

  static List<NewsSource> get defaultSources => [
    NewsSource(id: 'rmf24_polska', name: 'RMF24', rssUrl: 'https://www.rmf24.pl/fakty/polska/feed', categoryId: 'poland'),
    NewsSource(id: 'tvn24_najwazniejsze', name: 'TVN24', rssUrl: 'https://tvn24.pl/najwazniejsze.xml', categoryId: 'poland'),
    NewsSource(id: 'onet_wiadomosci', name: 'Onet', rssUrl: 'https://wiadomosci.onet.pl/.feed', categoryId: 'poland'),
    NewsSource(id: 'rp_polska', name: 'Rzeczpospolita', rssUrl: 'https://www.rp.pl/rss/1016', categoryId: 'poland'),
    NewsSource(id: 'interia_fakty', name: 'Interia Fakty', rssUrl: 'https://fakty.interia.pl/feed', categoryId: 'poland'),
    NewsSource(id: 'gazeta_pl_wiadomosci', name: 'Gazeta.pl', rssUrl: 'http://wiadomosci.gazeta.pl/pub/rss/wiadomosci.xml', categoryId: 'poland'),
    NewsSource(id: 'bbc_world', name: 'BBC News', rssUrl: 'http://feeds.bbci.co.uk/news/world/rss.xml', categoryId: 'world'),
    NewsSource(id: 'nyt_world', name: 'New York Times', rssUrl: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', categoryId: 'world'),
    NewsSource(id: 'guardian_world', name: 'The Guardian', rssUrl: 'https://www.theguardian.com/world/rss', categoryId: 'world'),
    NewsSource(id: 'aljazeera_world', name: 'Al Jazeera', rssUrl: 'https://www.aljazeera.com/xml/rss/all.xml', categoryId: 'world'),
    NewsSource(id: 'reuters_world', name: 'Reuters', rssUrl: 'https://www.reutersagency.com/feed/', categoryId: 'world'),
    NewsSource(id: 'money_pl', name: 'Money.pl', rssUrl: 'https://www.money.pl/rss/', categoryId: 'business'),
    NewsSource(id: 'business_insider_pl', name: 'Business Insider PL', rssUrl: 'https://businessinsider.com.pl/.feed', categoryId: 'business'),
    NewsSource(id: 'bankier_pl', name: 'Bankier.pl', rssUrl: 'https://www.bankier.pl/rss/wiadomosci.xml', categoryId: 'business'),
    NewsSource(id: 'pb_pl', name: 'Puls Biznesu', rssUrl: 'https://www.pb.pl/rss', categoryId: 'business'),
    NewsSource(id: 'rp_ekonomia', name: 'Rzeczpospolita Ekonomia', rssUrl: 'https://www.rp.pl/rss/ekonomia', categoryId: 'business'),
    NewsSource(id: 'gazetaprawna_pl', name: 'Dziennik Gazeta Prawna', rssUrl: 'http://rss.gazetaprawna.pl/GazetaPrawna', categoryId: 'business'),
    NewsSource(id: 'parkiet_com', name: 'Parkiet.com', rssUrl: 'https://www.parkiet.com/rss.xml', categoryId: 'business'),
    NewsSource(id: 'interia_biznes', name: 'Interia Biznes', rssUrl: 'http://kanaly.rss.interia.pl/biznes.xml', categoryId: 'business'),
    NewsSource(id: 'forsal_pl', name: 'Forsal.pl', rssUrl: 'http://rss.forsal.pl/Forsal', categoryId: 'business'),
    NewsSource(id: 'wnp_pl', name: 'WNP.pl (Przemysł)', rssUrl: 'https://www.wnp.pl/rss/serwis_rss_999.xml', categoryId: 'business'),
    NewsSource(id: 'next_gazeta_pl', name: 'Next.gazeta.pl', rssUrl: 'http://rss.gazeta.pl/pub/rss/next.xml', categoryId: 'business'),
    NewsSource(id: 'subiektywnie_o_finansach', name: 'Subiektywnie o Finansach', rssUrl: 'https://subiektywnieofinansach.pl/feed/', categoryId: 'business'),
    NewsSource(id: 'bnbn_pl', name: 'BNBN.pl', rssUrl: 'https://bnbn.pl/feed/', categoryId: 'business'),
    NewsSource(id: 'infor_pl', name: 'Infor.pl', rssUrl: 'https://www.infor.pl/rss/aktualnosci_prawno_gospodarcze.xml', categoryId: 'business'),
    NewsSource(id: 'forbes_pl', name: 'Forbes Polska', rssUrl: 'https://news.google.com/rss/search?q=site:forbes.pl&hl=pl&gl=PL&ceid=PL:pl', categoryId: 'business'),
    NewsSource(id: 'reuters_business', name: 'Reuters Business', rssUrl: 'https://openrss.org/www.reuters.com/business', categoryId: 'business'),
    NewsSource(id: 'wsj_business', name: 'Wall Street Journal', rssUrl: 'https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml', categoryId: 'business'),
    NewsSource(id: 'cnbc_business', name: 'CNBC Business', rssUrl: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147', categoryId: 'business'),
    NewsSource(id: 'sztuczna_inteligencja_pl', name: 'Sztuczna-Inteligencja.pl', rssUrl: 'https://www.sztucznainteligencja.org.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'aiot_pl', name: 'AIoT.pl', rssUrl: 'https://aiot.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'ai_pl', name: 'AI.pl', rssUrl: 'https://ai.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'genai_works', name: 'GenAI Works', rssUrl: 'https://medium.com/feed/generative-ai', categoryId: 'tech'),
    NewsSource(id: 'warsaw_ai', name: 'Warsaw.AI News', rssUrl: 'https://warsawai.substack.com/feed', categoryId: 'tech'),
    NewsSource(id: 'antyweb', name: 'Antyweb', rssUrl: 'https://antyweb.pl/feed', categoryId: 'tech'),
    NewsSource(id: 'spiders_web', name: "Spider's Web", rssUrl: 'https://spidersweb.pl/feed', categoryId: 'tech'),
    NewsSource(id: 'purepc', name: 'PurePC', rssUrl: 'https://www.purepc.pl/rss', categoryId: 'tech'),
    NewsSource(id: 'benchmark_pl', name: 'Benchmark.pl', rssUrl: 'http://www.benchmark.pl/rss/benchmark-pl.xml', categoryId: 'tech'),
    NewsSource(id: 'komputer_swiat', name: 'Komputer Świat', rssUrl: 'https://www.komputerswiat.pl/rss.xml', categoryId: 'tech'),
    NewsSource(id: 'innpoland', name: 'INNPoland.pl', rssUrl: 'https://innpoland.pl/rss', categoryId: 'tech'),
    NewsSource(id: 'mamstartup', name: 'MamStartup', rssUrl: 'https://mamstartup.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'mambiznes', name: 'Mambiznes.pl', rssUrl: 'https://mambiznes.pl/rss', categoryId: 'tech'),
    NewsSource(id: 'just_geek_it', name: 'Just Geek IT', rssUrl: 'https://geek.justjoin.it/feed', categoryId: 'tech'),
    NewsSource(id: 'itwiz', name: 'ITwiz', rssUrl: 'https://itwiz.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'brandsit', name: 'Brandsit.pl', rssUrl: 'https://brandsit.pl/feed/', categoryId: 'tech'),
    NewsSource(id: 'techcrunch', name: 'TechCrunch', rssUrl: 'https://techcrunch.com/feed/', categoryId: 'tech'),
    NewsSource(id: 'the_verge', name: 'The Verge', rssUrl: 'https://www.theverge.com/rss/index.xml', categoryId: 'tech'),
    NewsSource(id: 'probasket', name: 'Probasket', rssUrl: 'https://probasket.pl/feed/', categoryId: 'sport'),
    NewsSource(id: 'gwiazdy_basketu', name: 'Gwiazdy Basketu', rssUrl: 'https://gwiazdybasketu.pl/feed/', categoryId: 'sport'),
    NewsSource(id: 'szosty_gracz', name: 'Szósty Gracz', rssUrl: 'https://szostygracz.pl/feed/', categoryId: 'sport'),
    NewsSource(id: 'zkrainynba', name: 'Z Krainy NBA', rssUrl: 'https://zkrainynba.com/feed/', categoryId: 'sport'),
    NewsSource(id: 'rzutza3', name: 'RzutZa3', rssUrl: 'https://rzutza3.pl/feed/', categoryId: 'sport'),
    NewsSource(id: 'tvp_sport', name: 'TVP Sport', rssUrl: 'http://www.tvp.pl/rss.php?id=12', categoryId: 'sport'),
    NewsSource(id: 'polsat_sport', name: 'Polsat Sport', rssUrl: 'https://www.polsatsport.pl/rss/wszystkie.xml', categoryId: 'sport'),
    NewsSource(id: 'weszlo', name: 'Weszło', rssUrl: 'https://weszlo.com/feed/', categoryId: 'sport'),
    NewsSource(id: 'transfery_info', name: 'Transfery.info', rssUrl: 'https://transfery.info/rss', categoryId: 'sport'),
    NewsSource(id: 'sportowefakty', name: 'WP SportoweFakty', rssUrl: 'https://sportowefakty.wp.pl/rss.xml', categoryId: 'sport'),
    NewsSource(id: 'eurosport_pl', name: 'Eurosport PL', rssUrl: 'https://tvn24.pl/sport,4.xml', categoryId: 'sport'),
    NewsSource(id: 'sky_sports_pl', name: 'Sky Sports PL', rssUrl: 'https://www.skysports.com/rss/11661', categoryId: 'sport'),
    NewsSource(id: 'f1_official', name: 'Formula 1', rssUrl: 'https://www.formula1.com/en/latest/all.xml', categoryId: 'sport'),
    NewsSource(id: 'motogp_crash', name: 'MotoGP (Crash)', rssUrl: 'https://www.crash.net/rss/motogp', categoryId: 'sport'),
    NewsSource(id: 'wrc_dirtfish', name: 'WRC (DirtFish)', rssUrl: 'https://dirtfish.com/rally/wrc/feed/', categoryId: 'sport'),
    NewsSource(id: 'naszosie_pl', name: 'Naszosie.pl', rssUrl: 'https://naszosie.pl/feed/', categoryId: 'sport'),
    NewsSource(id: 'rowery_org', name: 'Rowery.org', rssUrl: 'https://rowery.org/feed/', categoryId: 'sport'),
    NewsSource(id: 'cyclingnews', name: 'Cyclingnews', rssUrl: 'https://www.cyclingnews.com/rss', categoryId: 'sport'),
    NewsSource(id: 'gravel_cyclist', name: 'Gravel Cyclist', rssUrl: 'https://www.gravelcyclist.com/feed/', categoryId: 'sport'),
    NewsSource(id: 'siatka_org', name: 'Siatka.org', rssUrl: 'https://siatka.org/feed/', categoryId: 'sport'),
    NewsSource(id: 'tennis_x', name: 'Tennis-X', rssUrl: 'http://feeds.feedburner.com/tennisx', categoryId: 'sport'),
    NewsSource(id: 'nature_news', name: 'Nature', rssUrl: 'http://feeds.nature.com/nature/rss/news', categoryId: 'science'),
    NewsSource(id: 'science_news', name: 'Science', rssUrl: 'https://www.science.org/rss/news_current.xml', categoryId: 'science'),
    NewsSource(id: 'plos_one', name: 'PLOS ONE', rssUrl: 'https://journals.plos.org/plosone/feed/rss', categoryId: 'science'),
    NewsSource(id: 'sci_american', name: 'Scientific American', rssUrl: 'http://rss.sciam.com/ScientificAmerican-Global', categoryId: 'science'),
    NewsSource(id: 'nasa_news', name: 'NASA News', rssUrl: 'https://www.nasa.gov/news-release/feed/', categoryId: 'science'),
    NewsSource(id: 'phys_org', name: 'Phys.org', rssUrl: 'https://phys.org/rss-feed/', categoryId: 'science'),
    NewsSource(id: 'nejm_news', name: 'NEJM', rssUrl: 'https://www.nejm.org/rss-feed/', categoryId: 'science'),
    NewsSource(id: 'the_lancet', name: 'The Lancet', rssUrl: 'https://www.thelancet.com/rssfeed/lancet.xml', categoryId: 'science'),
    NewsSource(id: 'jama_news', name: 'JAMA', rssUrl: 'https://jamanetwork.com/rss/site_3.xml', categoryId: 'science'),
    NewsSource(id: 'bmj_news', name: 'BMJ', rssUrl: 'https://www.bmj.com/rss/recent.xml', categoryId: 'science'),
    NewsSource(id: 'puls_medycyny', name: 'Puls Medycyny', rssUrl: 'https://pulsmedycyny.pl/rss', categoryId: 'science'),
    NewsSource(id: 'nauka_w_polsce', name: 'Nauka w Polsce', rssUrl: 'https://naukawpolsce.pl/all/rss.xml', categoryId: 'science'),
    NewsSource(id: 'kwantowo_pl', name: 'Kwantowo.pl', rssUrl: 'https://www.kwantowo.pl/feed/', categoryId: 'science'),
    NewsSource(id: 'projekt_pulsar', name: 'Projekt Pulsar', rssUrl: 'https://www.polityka.pl/rss/articles.xml?list=268', categoryId: 'science'),
    NewsSource(id: 'dziennik_naukowy', name: 'Dziennik Naukowy', rssUrl: 'https://dzienniknaukowy.pl/feed/', categoryId: 'science'),
    NewsSource(id: 'autocentrum', name: 'Autocentrum.pl', rssUrl: 'https://www.autocentrum.pl/rss/newsy.xml', categoryId: 'automotive'),
    NewsSource(id: 'autokult', name: 'WP Autokult', rssUrl: 'https://autokult.pl/rss/wszystkie', categoryId: 'automotive'),
    NewsSource(id: 'onet_moto', name: 'Onet Moto', rssUrl: 'https://wiadomosci.onet.pl/moto/.feed', categoryId: 'automotive'),
    NewsSource(id: 'moto_pl', name: 'Moto.pl', rssUrl: 'http://wiadomosci.gazeta.pl/pub/rss/moto.xml', categoryId: 'automotive'),
    NewsSource(id: 'interia_moto', name: 'Interia Motoryzacja', rssUrl: 'http://kanaly.rss.interia.pl/motoryzacja.xml', categoryId: 'automotive'),
    NewsSource(id: 'auto_swiat', name: 'Auto Świat', rssUrl: 'https://www.auto-swiat.pl/rss', categoryId: 'automotive'),
    NewsSource(id: 'magazyn_auto', name: 'Magazyn Auto (Motor)', rssUrl: 'https://rss.interia.pl/magazynauto.xml', categoryId: 'automotive'),
    NewsSource(id: 'top_gear_global', name: 'Top Gear (Global)', rssUrl: 'https://www.topgear.com/rss', categoryId: 'automotive'),
    NewsSource(id: 'automobilista', name: 'Automobilista', rssUrl: 'https://automobilista.com.pl/feed/', categoryId: 'automotive'),
    NewsSource(id: 'elektrowoz', name: 'Elektrowóz', rssUrl: 'https://elektrowoz.pl/feed/', categoryId: 'automotive'),
    NewsSource(id: 'autoblog_pl', name: "Spider's Web Autoblog", rssUrl: 'https://spidersweb.pl/autoblog/feed', categoryId: 'automotive'),
    NewsSource(id: 'green_car_congress', name: 'Green Car Congress', rssUrl: 'https://www.greencarcongress.com/rss.xml', categoryId: 'automotive'),
    NewsSource(id: 'samar_pl', name: 'IBRM Samar', rssUrl: 'https://news.google.com/rss/search?q=site:samar.pl&hl=pl&gl=PL&ceid=PL:pl', categoryId: 'automotive'),
    NewsSource(id: 'wrc_moto', name: 'WRC.net.pl', rssUrl: 'https://wrc.net.pl/feed/', categoryId: 'automotive'),
    NewsSource(id: 'sokol_oko_f1', name: 'Sokół Około F1', rssUrl: 'https://sokolimokiem.com/feed/', categoryId: 'automotive'),
    NewsSource(id: 'filmweb_news', name: 'Filmweb', rssUrl: 'https://news.google.com/rss/search?q=site:filmweb.pl&hl=pl&gl=PL&ceid=PL:pl', categoryId: 'culture'),
    NewsSource(id: 'naekranie', name: 'NaEkranie', rssUrl: 'https://naekranie.pl/feed', categoryId: 'culture'),
    NewsSource(id: 'filmozercy', name: 'Filmożercy', rssUrl: 'https://filmozercy.com/feed', categoryId: 'culture'),
    NewsSource(id: 'film_org_pl', name: 'Film.org.pl', rssUrl: 'https://film.org.pl/feed', categoryId: 'culture'),
    NewsSource(id: 'serialowa', name: 'Serialowa', rssUrl: 'https://www.serialowa.pl/feed', categoryId: 'culture'),
    NewsSource(id: 'upflix_vod', name: 'Upflix (VOD)', rssUrl: 'https://upflix.pl/feed/', categoryId: 'culture'),
    NewsSource(id: 'gram_popkultura', name: 'Gram.pl Popkultura', rssUrl: 'https://www.gram.pl/feed/', categoryId: 'culture'),
    NewsSource(id: 'spidersweb_rozrywka', name: "Spider's Web Rozrywka", rssUrl: 'https://spidersweb.pl/rozrywka/feed', categoryId: 'culture'),
    NewsSource(id: 'ppe_kino', name: 'PPE.pl Kino', rssUrl: 'https://www.ppe.pl/rss/kino.xml', categoryId: 'culture'),
    NewsSource(id: 'gry_online_serialomaniak', name: 'GOL Serialomaniak', rssUrl: 'https://www.gry-online.pl/rss/serialomaniak.xml', categoryId: 'culture'),
    NewsSource(id: 'tanuki_pl', name: 'Tanuki.pl (Anime)', rssUrl: 'http://anime.tanuki.pl/rss.xml', categoryId: 'culture'),
    NewsSource(id: 'kultura_onet', name: 'Kultura Onet', rssUrl: 'https://kultura.onet.pl/.feed', categoryId: 'culture'),
    NewsSource(id: 'wyborcza_kultura', name: 'Wyborcza Kultura', rssUrl: 'http://rss.gazeta.pl/pub/rss/kultura.xml', categoryId: 'culture'),
    NewsSource(id: 'dwutygodnik', name: 'Dwutygodnik', rssUrl: 'https://www.dwutygodnik.com/rss', categoryId: 'culture'),
    NewsSource(id: 'kultura_liberalna', name: 'Kultura Liberalna', rssUrl: 'https://kulturaliberalna.pl/feed/', categoryId: 'culture'),
    NewsSource(id: 'vogue_kultura', name: 'Vogue Polska', rssUrl: 'https://www.vogue.pl/k/kultura/feed', categoryId: 'culture'),
    NewsSource(id: 'imponderabilia_pod', name: 'Imponderabilia', rssUrl: 'https://anchor.fm/s/18384218/podcast/rss', categoryId: 'culture'),
    NewsSource(id: 'jakbyniepaczec_pod', name: 'Jakbyniepaczec', rssUrl: 'https://anchor.fm/s/3cc71778/podcast/rss', categoryId: 'culture'),
    NewsSource(id: 'fly4free', name: 'Fly4free', rssUrl: 'https://www.fly4free.pl/feed/', categoryId: 'travel'),
    NewsSource(id: 'wakacyjni_piraci', name: 'Wakacyjni Piraci', rssUrl: 'https://www.wakacyjnipiraci.pl/feed/', categoryId: 'travel'),
    NewsSource(id: 'loter_pl', name: 'Loter.pl', rssUrl: 'https://www.loter.pl/rss.xml', categoryId: 'travel'),
    NewsSource(id: 'mleczne_podroze', name: 'Mleczne Podróże', rssUrl: 'https://mlecznepodroze.pl/feed/', categoryId: 'travel'),
    NewsSource(id: 'esky_magazyn', name: 'eSky Magazyn', rssUrl: 'https://www.esky.pl/porady-dla-podroznych/feed/', categoryId: 'travel'),
    NewsSource(id: 'wakacje_pl_mag', name: 'Wakacje.pl Magazyn', rssUrl: 'https://www.wakacje.pl/magazyn/feed/', categoryId: 'travel'),
    NewsSource(id: 'skyscanner_news', name: 'Skyscanner News', rssUrl: 'https://news.google.com/rss/search?q=site:skyscanner.pl&hl=pl&gl=PL&ceid=PL:pl', categoryId: 'travel'),
    NewsSource(id: 'pasazer_com', name: 'Pasazer.com', rssUrl: 'https://www.pasazer.com/rss/', categoryId: 'travel'),
    NewsSource(id: 'podroze_pl', name: 'Podróże.pl', rssUrl: 'https://www.podroze.pl/rss/', categoryId: 'travel'),
    NewsSource(id: 'nat_geo_traveler', name: 'NG Traveler', rssUrl: 'https://www.national-geographic.pl/traveler/rss', categoryId: 'travel'),
    NewsSource(id: 'onet_podroze', name: 'Onet Podróże', rssUrl: 'https://podroze.onet.pl/.feed', categoryId: 'travel'),
    NewsSource(id: 'geoportal_news', name: 'Geoportal Wiadomości', rssUrl: 'https://www.geoportal.gov.pl/rss/wiadomosci.xml', categoryId: 'travel'),
    NewsSource(id: 'lonely_planet', name: 'Lonely Planet', rssUrl: 'https://www.lonelyplanet.com/news/rss', categoryId: 'travel'),
    NewsSource(id: 'wp_turystyka', name: 'WP Turystyka', rssUrl: 'https://turystyka.wp.pl/rss.xml', categoryId: 'travel'),
    NewsSource(id: 'noizz_pl', name: 'Noizz.pl', rssUrl: 'https://noizz.pl/.feed', categoryId: 'lifestyle'),
    NewsSource(id: 'k_mag', name: 'K MAG', rssUrl: 'https://kmag.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'f5_trendbook', name: 'F5 Trendbook', rssUrl: 'https://www.f5.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'newonce_net', name: 'newonce.net', rssUrl: 'https://news.google.com/rss/search?q=site:newonce.net&hl=pl&gl=PL&ceid=PL:pl', categoryId: 'lifestyle'),
    NewsSource(id: 'vogue_pl_life', name: 'Vogue Polska', rssUrl: 'https://www.vogue.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'elle_pl', name: 'Elle.pl', rssUrl: 'https://www.elle.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'glamour_pl', name: 'Glamour.pl', rssUrl: 'https://www.glamour.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'zwierciadlo_pl', name: 'Zwierciadlo.pl', rssUrl: 'https://zwierciadlo.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'sens_psychologia', name: 'Magazyn Sens', rssUrl: 'https://zwierciadlo.pl/psychologia/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'kobieta_pl', name: 'Kobieta.pl', rssUrl: 'https://www.kobieta.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'label_magazine', name: 'Label Magazine', rssUrl: 'https://labelmagazine.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'kukbuk_pl', name: 'Kukbuk', rssUrl: 'https://kukbuk.pl/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'magazyn_ustka', name: 'Magazyn Ustka', rssUrl: 'https://magazynustka.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'onet_kobieta', name: 'Onet Kobieta', rssUrl: 'https://kobieta.onet.pl/.feed', categoryId: 'lifestyle'),
    NewsSource(id: 'gazeta_kobieta', name: 'Gazeta.pl Kobieta', rssUrl: 'https://kobieta.gazeta.pl/pub/rss/kobieta.xml', categoryId: 'lifestyle'),
    NewsSource(id: 'kwestia_smaku', name: 'Kwestia Smaku', rssUrl: 'https://www.kwestiasmaku.com/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'moje_wypieki', name: 'Moje Wypieki', rssUrl: 'https://mojewypieki.com/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'ania_gotuje', name: 'Ania Gotuje', rssUrl: 'https://aniagotuje.pl/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'white_plate', name: 'White Plate', rssUrl: 'https://whiteplate.com/feed', categoryId: 'lifestyle'),
    NewsSource(id: 'jadlonomia', name: 'Jadłonomia', rssUrl: 'https://www.jadlonomia.com/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'sztosowe_pl', name: 'Sztosowe.pl', rssUrl: 'https://sztosowe.pl/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'make_cooking_easier', name: 'Make Cooking Easier', rssUrl: 'https://makecookingeasier.pl/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'ervegan_pl', name: 'Ervegan', rssUrl: 'https://ervegan.com/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'smaker_pl', name: 'Smaker.pl', rssUrl: 'https://smaker.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'przepisy_pl', name: 'Przepisy.pl', rssUrl: 'https://www.przepisy.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'beszamel_pl', name: 'Beszamel (SE)', rssUrl: 'https://beszamel.se.pl/rss/', categoryId: 'lifestyle'),
    NewsSource(id: 'przyslij_przepis', name: 'Przyslijprzepis.pl', rssUrl: 'https://www.przyslijprzepis.pl/rss', categoryId: 'lifestyle'),
    NewsSource(id: 'food_and_design', name: 'Food and Design', rssUrl: 'https://foodanddesign.pl/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'pozywka_pl', name: 'Pożywka', rssUrl: 'https://pozywka.pl/feed/', categoryId: 'lifestyle'),
    NewsSource(id: 'nawidelcu_pl', name: 'NaWidelcu.pl', rssUrl: 'https://nawidelcu.pl/feed/', categoryId: 'lifestyle'),
  ];
}
